micronaut:
  application:
    name: helloWorld
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  security:
    authentication: bearer


datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    packages-to-scan:
      - 'ru.pudgy.vertex.model'
    entity-scan:
      packages: 'ru.pudgy.vertex.model.entity'
    properties:
      hibernate:
        bytecode:
          provider: none
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      locations: classpath:db/migration


text:
  annotationBuilder: Simple

